// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jloyjcanvtolhgodeupf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impsb3lqY2FudnRvbGhnb2RldXBmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNzEzODgsImV4cCI6MjA3MDg0NzM4OH0.lal78KCj_sFdSzkHb2mtdYtkrY7MwXtyL4sTpVvcb3g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});